# Generated by Django 6.0 on 2025-12-24 21:36

import core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('country', models.CharField(default='Germany', max_length=70)),
                ('city', models.CharField(max_length=70)),
                ('land', models.CharField(blank=True, max_length=30)),
                ('street', models.CharField(max_length=50)),
                ('postal_code', models.CharField(max_length=5)),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
                'db_table': 'addresses',
                'indexes': [models.Index(fields=['city'], name='addresses_city_dfd875_idx'), models.Index(fields=['postal_code'], name='addresses_postal__0e4029_idx')],
            },
        ),
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('name', models.CharField(max_length=70, unique=True)),
                ('category', models.CharField(choices=[('basic', 'Basic'), ('comfort', 'Comfort'), ('premium', 'Premium')], max_length=20)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Amenity',
                'verbose_name_plural': 'Amenities',
                'db_table': 'amenities',
                'ordering': ['category', 'name'],
                'indexes': [models.Index(fields=['category'], name='amenities_categor_5be04d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('house_type', models.CharField(choices=[('house', 'House'), ('room', 'Room'), ('apartment', 'Apartment'), ('studio', 'Studio')], max_length=20)),
                ('max_stayers', models.PositiveIntegerField(validators=[core.validators.validate_positive_number])),
                ('bedrooms', models.PositiveIntegerField(validators=[core.validators.validate_positive_number])),
                ('bathrooms', models.PositiveIntegerField(validators=[core.validators.validate_positive_number])),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10, validators=[core.validators.validate_positive_price])),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='listing', to='listings.address')),
                ('amenities', models.ManyToManyField(blank=True, related_name='listings', to='listings.amenity')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Listing',
                'verbose_name_plural': 'Listings',
                'db_table': 'listings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListingImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('img', models.ImageField(upload_to='listings/%Y/%m/%d/')),
                ('main', models.BooleanField(default=False)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.listing')),
            ],
            options={
                'verbose_name': 'Listing image',
                'verbose_name_plural': 'Listing images',
                'db_table': 'listing_imgs',
                'ordering': ['-main', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['owner'], name='listings_owner_i_d70a22_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['is_active'], name='listings_is_acti_fd46bf_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['house_type'], name='listings_house_t_b63111_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['price_per_night'], name='listings_price_p_96809c_idx'),
        ),
    ]
